notifications:
    email:
        on_success: never
        on_failure: always

sudo: required

services:
  - docker

env:
    global:
        - REPO=idelsink/mexdown
    matrix:
        - DISTRO=fedora23
        - DISTRO=fedora24

script:
    - docker build -t $REPO:$DISTRO $DISTRO/
